source "http://rubygems.org"

group :development do
  gem 'rake', '~> 12.3.3'
  gem 'rack', '~> 3.1.8'
  gem 'jekyll', '~> 4.3.4'
  gem 'rdiscount', '~> 1.6.8'
  gem 'pygments.rb', '~> 0.2.12'
  gem 'RedCloth', '~> 4.3.3'
  gem 'haml', '~> 5.0.0'
  gem 'compass', '~> 0.12.1'
  gem 'rubypants', '~> 0.2.0'
  gem 'rb-fsevent', '~> 0.11'
  gem 'stringex', '~> 1.4.0'
  gem 'liquid', '~> 4.0.4'

  gem 'json', '~> 2.3.0'
end

gem 'sinatra', '~> 4.0.0'
